source 'https://rubygems.org'

gem 'rails', '~> 4.2.5'

gem 'attr_encrypted'
gem 'bcrypt'
gem 'bootstrap-sass'
gem 'clearance'
gem 'coffee-rails'
gem 'doorkeeper'
gem 'dotenv-rails'
gem 'global'
gem 'grape'
gem 'grape-entity'
gem 'grape-kaminari'
gem 'jbuilder'
gem 'jquery-rails'
gem 'jquery-turbolinks'
gem 'jquery-ui-rails'
gem 'iso8601'
gem 'rest-client'
gem 'pg'
gem 'pry-rails'
gem 'rails-i18n'
gem 'rollbar'
gem 'sass-rails'
gem 'savon'
gem 'simple_form'
gem 'skylight'
# gem 'therubyracer'
gem 'turbolinks'
gem 'uglifier'

group :development, :test do
  gem 'byebug'
  gem 'capistrano'
  gem 'capistrano-passenger'
  gem 'capistrano-rails'
  gem 'database_cleaner'
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'foreman'
  gem 'rspec-rails'
  gem 'shoulda-matchers'
  gem 'spring'
  gem 'spring-commands-rspec'
  gem 'thin'
end

group :test do
  gem 'capybara-webkit'
  gem 'launchy'
  gem 'simplecov', require: false
  gem 'vcr'
  gem 'webmock'
end
