default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  template: template0

development:
  <<: *default
  database: ebipon_development

test:
  <<: *default
  database: ebipon_test

production:
  <<: *default
  database: ebipon_production
